### PR TITLE
Added the memory monitorint package prmon

### PR DESCRIPTION
**Pull request by yesw2000**

### CODE REVIEW

**Comment by timj** [comment]
Polict is that we use branch names for all pull requests and the branch name must be "tickets/DM-nnn" so in this case the branch should be `tickets/DM-32579`.

I'm kind of surprised that this repo still uses `master`.

**Comment by yesw2000** [comment]
I double that I have the permission to make a new branch in that repo.

**Comment by timj** [comment]
I mean make a new branch in your fork and create a new PR.

**Comment by yesw2000** [comment]
I just made a new pull request-13, based a new branch tickets/DM-32579. So I close this request-12.

**Pull request closed without merging**
